### ISSUE TITLE
Mail forward Error

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa-webmail#106]
If you forward a mail over the webmail to another user, the original mailaddress in the body is away, there is only the name of the original sender but no mail address

**Comment by tonioo** [comment]
Which version? With the HTML editor or not?

**Comment by tonioo** [comment]
@WASDIT ping

**Comment by WASDIT** [comment]
Maybe it is already solved, i will check it with the customer.

**Comment by tonioo** [comment]
@WASDIT any news?

**Comment by tonioo** [comment]
@WASDIT ping
