### ISSUE TITLE
After Upgrade to webmail 1.2.1 modoboa not shows the upgrade

### ISSUE THREAD

**Issue by MBadberg** [modoboa/modoboa-webmail#107]
I have installed the upgrade for webmail, like the docs says. But after restart of nginx modoboa shows still the old version of webmail. 1.2.0
The output from upgrade process is in the txt file. 

[modo.upgrade-webmail.txt](https://github.com/modoboa/modoboa-webmail/files/1325841/modo.upgrade-webmail.txt)
I'm sorry for the layout. it is broken, but everything is in the txt file :-)

**Comment by tonioo** [comment]
You need to restart uwsgi, not nginx. 
One question: have you run the collectstatic command more than once?

**Comment by MBadberg** [comment]
Yes, i've run all the commands.

Okay, there should be an addition in the docs. they are not clearly enough, i think. A lil bit more explanation, what the installer installs.

Now it works, Thanks.
