### ISSUE TITLE
Address book

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-webmail#11]
_From @tonioo on December 4, 2013 15:44_

**Originally created by Antoine Nguyen on 2012-10-21T09:42:45Z**

Implement (or find a django application) to provide address books to users.

_Copied from original issue: tonioo/modoboa#321_

**Comment by sin88** [comment]
Is there a chance that the implementation of address book to modoboa-webmail will be soon. In point of fact address book in most other webmails is a core functionality... It would be great to see it in modoba. Is there any simple and verified workaround to have address book?

**Comment by tonioo** [comment]
This feature could be added to the webmail, it just requires time or help. If you are familiar with python/django, don't hesitate to help :-)

**Comment by sin88** [comment]
I'm newbie in python. I discovered modoboa recently and it is what I was searching for a long time. So after some time if I will know more about python maybe I will help. First of all I added a little polish accents on www.transifex.com ;)

**Comment by tonioo** [comment]
@sin88 FYI, I'm working on it! https://github.com/modoboa/modoboa-contacts
