### ISSUE TITLE
Mail Forward Attachment Error

### ISSUE THREAD

**Issue by EDV4BIZ** [modoboa/modoboa-webmail#110]
Hello,
if we forward a mail in the webmail the attachment is removed in the forward mail, is it possible if i click on forward that the attachment will also in the forward mail as attachment?

**Comment by tonioo** [comment]
Actually, the attachments are not displayed when you forward a message BUT they are sent (you can try).

**Comment by dakolta** [comment]
I am having the same problem, on 1.10.6.
Try to forward an email with an attachment, the receiving user reports that there is no attachment.

**Comment by specialseth** [comment]
Could you point out where I can find documentation on how to upgrade from Webmail 1.5.0, which is install using modoboa-installer, to Webmail 1.6.0?
