### ISSUE TITLE
After update 1.2.1 compose shows internal error

### ISSUE THREAD

**Issue by ociotec** [modoboa/modoboa-webmail#111]
I've updated today the modoboa-webmail package following instructions at http://modoboa.readthedocs.io/en/latest/upgrade.html.

When I click on compose new email a red pop-up window appears with _Internal error_ message.

I've checked server logs (`/var/log/uwsgi/app/modoboa_instance.log`), but it doesn't reveal anything:

    ************** [pid: 1037|app: 1|req: 23/37] ************* () {50 vars in 1093 bytes}
    [Sun Oct  1 10:48:29 2017] GET /webmail/?action=compose&_=************** =>
    generated 870 bytes in 36 msecs (HTTP/1.1 500) 4 headers in 160 bytes (1 switches on core 0)

Any clue? maybe it's something related to new package version? I've already checked milestone 1.2.2 but it seems that the only issue #108 is not related with my problem.

Thanks in advance!

**Comment by tonioo** [comment]
@ociotec Set DEBUG to True inside settings.py, reload uwsgi and open your web developer console, track the response. You should see a more explicit python trace.

**Comment by ociotec** [comment]
@tonioo thanks for the quick response.

I found 2 errors in the web console, about 2 resource files not found:
* https://*********/sitestatic/font-awesome/fonts/fontawesome-webfont.woff2
* https://*********/sitestatic/ckeditor/ckeditor/ckeditor.js

Before you ask for it, I did ran the sitestatic regeneration via (I did it again before writting this just in case...):

    python manage.py collectstatic

Did I miss something during the upgrade? Thanks.

**Comment by ociotec** [comment]
I've try to find those statics in the `instance/sitestatic` folder, but they were not present at the expected paths...

I downloaded ckeditor & fontawesome from respective web pages, and I put them in the expected path (I mean the paths described in my previous comment).

After this I restarted uwsgi, in the web console the resource errors dissapeared, but I still see the internal error and I cannot compose or reply any message (I guess anything related with ckeditor).

I also checked my preferences (in order to disable ckeditor) but it's empty! I just see the title _Preferences Customize Modoboa_ and the _Save_ button (I guess I should see some settings in the middle of them...

**Comment by ociotec** [comment]
Is there any progress regarding this issue? or something I can do to work-around it? Or any other log or info to report? Thanks in advance.

**Comment by tonioo** [comment]
@ociotec Without a proper trace, I can't help you. With DEBUG set to True, watch your web console and look for a request returning a 500 error then look at the response, you should get interesting information.

**Comment by tonioo** [comment]
@ociotec ping

**Comment by ociotec** [comment]
@tonioo sorry for the delay... I tried several times until I found proper tab in firefox dev tools...

I get this error in the response (`500 Internal Server Error`):

```
UnicodeEncodeError at /webmail/
'ascii' codec can't encode character u'\xe1' in position 24: ordinal not in range(128)

Request Method: GET
Request URL: https://***********/webmail/?action=compose&_=************
Django Version: 1.10.8
Python Executable: /usr/bin/uwsgi-core
Python Version: 2.7.12
Python Path: ['.', '', '/srv/modoboa/env/lib/python2.7', '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu', '/srv/modoboa/env/lib/python2.7/lib-tk', '/srv/modoboa/env/lib/python2.7/lib-old', '/srv/modoboa/env/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/srv/modoboa/env/local/lib/python2.7/site-packages', '/srv/modoboa/env/lib/python2.7/site-packages']
Server time: Wed, 1 Nov 2017 18:38:37 +0100
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa_amavis',
 'modoboa_pdfcredentials',
 'modoboa_postfix_autoreply',
 'modoboa_sievefilters',
 'modoboa_stats',
 'modoboa_webmail',
 'modoboa_dmarc')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')


Traceback:  

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/lib.py" in wrapped_f
  40.                 return f(request, *args, **kwargs)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/views.py" in index
  622.         response = globals()[action](request)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/views.py" in compose
  474.     return render_compose(request, form, url, insert_signature=True)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/views.py" in render_compose
  434.         signature = EmailSignature(request.user)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/signature.py" in __init__
  18.             getattr(self, "_format_sig_%s" % dformat)(content)

File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/signature.py" in _format_sig_html
  26.         content = "---<br>{}".format(content)

Exception Type: UnicodeEncodeError at /webmail/
Exception Value: 'ascii' codec can't encode character u'\xe1' in position 24: ordinal not in range(128)
```

**Comment by ociotec** [comment]
It seems to be a problem when compose is trying to insert my signature... I tried to change the signature but then I realized preferences view (under my profile settings is empty):

![settings](https://user-images.githubusercontent.com/9693805/32288785-4acdf49c-bf35-11e7-9e16-bf70cacad87b.png)

If I debug this request, a red strip (at web dev tools top) says cannot load "https://********/sitestatic/core/css/userprefs.css". If I try to download this file, I get an empty file...

**Comment by tonioo** [comment]
@ociotec That's strange, I tried to reproduce this issue on the official demo using non-ascii characters in the signature and it works. Can you tell me what's the content of your signature?
About the CSS file, looks like it is actually empy. I'll remove this obsolete file.

**Comment by ociotec** [comment]
How can I delete/edit my signature? As I mentioned before in the screenshot, preferences view is empty... (I guess due to the same error).
Is it stored in database (I didn't find it there)? or in a file? Please give me a hint regarding signature locations.
Thanks in advance.

**Comment by tonioo** [comment]
It is stored in database using a JSON field. Look at the core_user table, column _parameters.

**Comment by tonioo** [comment]
@ociotec Any news about this?

**Comment by ociotec** [comment]
Sorry for the delayer answer...

I reset preferences with:

```sql
update core_user set _parameters = '{}' where username = 'xxxx@xxxx.com';
```

But nothing changed.

**Comment by tonioo** [comment]
@ociotec I released a new version yesterday. Could you please try it?

**Comment by ociotec** [comment]
@tonioo I've updated this morning before writting...

I followed typicall upgrading instructions:

```bash
$ pip install modoboa modoboa-admin modoboa-amavis modoboa-dmarc modoboa-imap-migration \
  modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-radicale modoboa-sievefilters \
  modoboa-stats modoboa-webmail --upgrade
```

At Modoboa admin view:

Name | Installed version | Last version
-- | -- | --
Modoboa | 1.9.1 | 1.9.1
Amavis frontend | 1.1.3 | 1.1.3
DMARC tools | 1.0.2 | 1.0.2
PDF credentials | 1.2.1 | 1.2.1
Postfix autoreply | 1.2.1 | 1.2.1
Sieve filters | 1.2.0 | 1.2.0
Statistics | 1.2.2 | 1.2.2
Webmail | 1.2.3 | 1.2.3

**Comment by tonioo** [comment]
This is not the recommanded way to upgrade a modoboa plugin. Have you seen this: http://modoboa.readthedocs.io/en/latest/upgrade.html#extensions?

**Comment by tonioo** [comment]
@ociotec ping
