### ISSUE TITLE
Cross-site scripting (XSS) in the webmail interface 

### ISSUE THREAD

**Issue by bl00m** [modoboa/modoboa-webmail#112]
Hi,
I found out that the webmail is vulnerable to XSS injections.
If you put a <script> tag in the mail subject or body, it will be executed when the recipient open is mailbox on modoboa.
That's pretty dangerous because anyone could just send a mail with a malicious script to do actions that are supposed to be reserved to mailbox owner.
It could for example send mails, edit user settings, etc...

# Example
![xss1](http://image.noelshack.com/fichiers/2017/40/2/1507021289-xss1.png)
![xss2](http://image.noelshack.com/fichiers/2017/40/2/1507021289-xss2.png)

**Comment by tonioo** [comment]
@bl00m Thank you for reporting this, I'll fix it for the next release.
