### ISSUE TITLE
Another XSS in the 'From' field

### ISSUE THREAD

**Issue by bl00m** [modoboa/modoboa-webmail#114]
Hi,
I looked at the commit that fix the XSS issues I reported (#113) and I see that the 'From' field is still considered safe.
I didn't think to it in the first place, but it's not safe because you could put a script tag in your firstname or lastname and it will run in the recipient mailbox.
The Cc and Bcc fields seems ok because they don't display firstname and lastname. And I don't think email addresses allow <script> tag.

**Comment by tonioo** [comment]
@bl00m I confirm your analysis, it is not safe. The fix is a bit more difficult than the previous one but I'll try to do it asap.
