### ISSUE TITLE
Error: Permission denied: A mailbox is required

### ISSUE THREAD

**Issue by jteeuw** [modoboa/modoboa-webmail#117]
Did a fresh install on Debian9 with the modoboa-installer.
I created a domain and a mail user , but whenn i open the webmail i get the following  

Error: Permission denied: A mailbox is required

**Comment by tonioo** [comment]
What kind of user did you create?

**Comment by jteeuw** [comment]
I created a account (simple user role ) in the identities menu, user account has an email address within the domain

**Comment by tonioo** [comment]
Can you check the Mail tab to see if the email is filled?

**Comment by jteeuw** [comment]
the mail tab of the user is filled in with a email adress

**Comment by tonioo** [comment]
Ok. Just to make sure, are you connected with the user you created?

**Comment by jteeuw** [comment]
Thanks, my mistake , i browsed directly to https//mydomain/webmail
