### ISSUE TITLE
KeyError at /webmail/getmailcontent

### ISSUE THREAD

**Issue by mirtouf** [modoboa/modoboa-webmail#120]
Bonjour,

I found other related issue with webmail that may be related to this bugreport but without debug, I cannot tell is I describe the same bug.
My setup is modoboa 1.9.1 and webmail 1.2.1 in a virtual environment
Trying to open an email end with an error 500 in the browser's console.

Setting debug = true in settings.py gives this information:

Request Method: | GET
-- | --
https://mydomain/webmail/getmailcontent?mbox=INBOX&mailid=5942&links=1
1.10.8
KeyError
'plain'
/home/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py in body, line 138
/usr/bin/uwsgi-core
2.7.13
['.',  '',  '/home/modoboa/env/lib/python2.7',  '/home/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/home/modoboa/env/lib/python2.7/lib-tk',  '/home/modoboa/env/lib/python2.7/lib-old',  '/home/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/home/modoboa/env/local/lib/python2.7/site-packages',  '/home/modoboa/env/lib/python2.7/site-packages']
Mon, 16 Oct 2017 16:32:22 +0000

Environment:

Request Method: GET
Request URL: https://mydomain/webmail/getmailcontent?mbox=INBOX&mailid=5942&links=1

Django Version: 1.10.8
Python Version: 2.7.13
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'rest_framework',
 'rest_framework.authtoken',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa_dmarc',
 'modoboa_imap_migration',
 'modoboa_pdfcredentials',
 'modoboa_pfxadmin_migrate',
 'modoboa_postfix_autoreply',
 'modoboa_radicale',
 'modoboa_sievefilters',
 'modoboa_stats',
 'modoboa_webmail')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:

File "/home/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/home/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/home/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/lib.py" in wrapped_f
  40.                 return f(request, *args, **kwargs)

File "/home/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/views.py" in getmailcontent
  538.         "mailbody": email.body if email.body else ""

File "/home/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imapemail.py" in body
  138.             for part in self.bs.contents[self.mformat]:

Exception Type: KeyError at /webmail/getmailcontent
Exception Value: 'plain' 

For some messages redacted in pure text, no error is shown (code 200) but the body of the message is displayed as empty even if a reply makes the body appearing in the composer.
Of course, using an alternate webmail or a heavy client like Thunderbird gives no error on displaying a message.

**Comment by mirtouf** [comment]
I modified some nginx options to make them less restrictive (concerning framing) and it seems to prevent these error to happen but it also seems a poorly designed html message can make appearing other types of errors. I will investigate later.

**Comment by tonioo** [comment]
@mirtouf Do you have access to the message which caused this trace?

**Comment by mirtouf** [comment]
Sorry, I cannot find again the message for the moment. I was sure I go an other error when trying to open the message.
