### ISSUE TITLE
Reply to Mail sends to wrong recipient

### ISSUE THREAD

**Issue by bot315** [modoboa/modoboa-webmail#121]
## Impacted versions
> Modoboa: 1.9.0
> Webmail: 1.2.1

## Steps to reproduce
Send a Mail with a displayname containing a comma, and answer it.
Mailheader looks like:
`From: "Doe, John" <john.doe@example.com>`

## Current behavior
To-field contains:
`"Doe, John" <john.doe@example.com>`

Mail gets send to Doe@mydomain.com and to John@mydomain.com but not to john.doe@example.com

Snippet from Postfix-log:
`Oct 25 19:35:50 mx.mydomain.com postfix/smtp[30992]: 9A52D8041B: to=<Doe@mydomain.com>, orig_to=<Doe>, relay=localhost[::1]:10024, delay=0.29, delays=0.03/0/0/0.26, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as D302980465)`
`Oct 25 19:35:50 mx.mydomain.com postfix/smtp[30992]: 9A52D8041B: to=<John@mydomain.com>, orig_to=<John>, relay=localhost[::1]:10024, delay=0.29, delays=0.03/0/0/0.26, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as D302980465)`

**Comment by fyfe** [comment]
This isn't the correct fix see my comment on modoboa/modoboa#1310
