### ISSUE TITLE
Upgrade 1.2.1 to 1.2.2

### ISSUE THREAD

**Issue by plvsouza** [modoboa/modoboa-webmail#124]
How can I upgrade?
I try `pip install --upgrade modoboa-webmail` but the web admin still shows I have to upgrade even I reboot the server

**Comment by tonioo** [comment]
The right command to run is ``pip install modoboa-webmail==1.2.2``. The online documentation will also help you: http://modoboa.readthedocs.io/en/latest/upgrade.html#extensions. Don't forget to reload uwsgi after the operation.

**Comment by plvsouza** [comment]
I try this:
`
pip install modoboa-sievefilters==1.2.0
pip install modoboa-webmail==1.2.2
systemctl restart uwsgi
systemctl restart nginx
`
but the web admin still shows I have to upgrade

**Comment by plvsouza** [comment]
I also tried
```
pip install modoboa-sievefilters==1.2.0
pip install modoboa-webmail==1.2.2
cd /srv/modoboa/instance
python manage.py migrate
python manage.py collectstatic
systemctl restart uwsgi
systemctl restart nginx
```
but the result is the same
