### ISSUE TITLE
Internal Error accessing INBOX features

### ISSUE THREAD

**Issue by iAdson** [modoboa/modoboa-webmail#129]
Hi,

We're actually facing a issue after using the modoboa-installer on a fresh new Virtual Machine. 

Specs are:

Debian 8.9.0
2go RAM
2 vCPU (2,50GHz)

No errors are displayed during the installation and we can connect to the GUI portal with the default admin/password. But after creating a domain and simple test users, when we attempt to connect with one on those and go to the webmail section or for example the filters settings, we get the error:
<img width="778" alt="error" src="https://user-images.githubusercontent.com/32452291/32850514-af9776de-ca32-11e7-9bd1-78d30a328129.png">

Please find bellow some informations of the version used:

> Modoboa               -> 1.9.1
> Amavis frontend   -> 1.1.3
> Contacts                -> 0.4.0
> PDF credentials    -> 1.2.1
> Postfix autoreply  -> 1.2.1
> Sieve filters           -> 1.2.0
> Statistics               -> 1.2.2
> Webmail                -> 1.2.2

Regards,
_-Maremu Team_

**Comment by tonioo** [comment]
@iAdson Can you set DEBUG to True inside settings.py and reload uwsgi please? You should see something more verbose.

**Comment by iAdson** [comment]
@tonioo Thanks for the assist!

I managed to determine the issue after taking a look at the debug error message: apparently the problem was my password.

As a french user, I got a french keyboard with special keys like the 'ç' and other stuffs that doesn't exist in other countries (I guess?).
So it couldn't encode and decode the password I set on the account. I tried to create a new one with a standart password and all worked fine.

Here is the error message I got:

![image](https://user-images.githubusercontent.com/32452291/32902725-7054787a-caf3-11e7-8eb5-b161ea7493e4.png)

Hope it will be patch in the future !

Regards,
_-Maremu Team_

**Comment by tonioo** [comment]
@iAdson Ok I see but could you please paste the full trace?

**Comment by iAdson** [comment]
@tonioo Sure, see bellow the paste of it:

> Environment:
> 
> 
> Request Method: GET
> Request URL: https://mail.maremu.eu/webmail/
> 
> Django Version: 1.10.8
> Python Version: 2.7.9
> Installed Applications:
> ('django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.sites',
>  'django.contrib.staticfiles',
>  'reversion',
>  'ckeditor',
>  'ckeditor_uploader',
>  'rest_framework',
>  'rest_framework.authtoken',
>  'modoboa',
>  'modoboa.core',
>  'modoboa.lib',
>  'modoboa.admin',
>  'modoboa.relaydomains',
>  'modoboa.limits',
>  'modoboa.parameters',
>  'modoboa_amavis',
>  'modoboa_pdfcredentials',
>  'modoboa_postfix_autoreply',
>  'modoboa_sievefilters',
>  'modoboa_stats',
>  'modoboa_webmail',
>  'modoboa_contacts',
>  'webpack_loader')
> Installed Middleware:
> ('x_forwarded_for.middleware.XForwardedForMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.locale.LocaleMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'modoboa.core.middleware.LocalConfigMiddleware',
>  'modoboa.lib.middleware.AjaxLoginRedirect',
>  'modoboa.lib.middleware.CommonExceptionCatcher',
>  'modoboa.lib.middleware.RequestCatcherMiddleware')
> 
> 
> 
> Traceback:
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
>   42.             response = get_response(request)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
>   249.             response = self._get_response(request)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
>   187.                 response = self.process_exception_by_middleware(e, request)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
>   185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
>   185.                     return func(*args, **kwargs)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
>   185.                     return func(*args, **kwargs)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
>   23.                 return view_func(request, *args, **kwargs)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/lib.py" in wrapped_f
>   40.                 return f(request, *args, **kwargs)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/views.py" in index
>   631.         imapc = get_imapconnector(request)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py" in get_imapconnector
>   796.                           password=request.session["password"])
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/connections.py" in __call__
>   31.                 super(ConnectionsManager, cls).__call__(**kwargs)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py" in __init__
>   185.         self.login(user, password)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py" in login
>   284.         data = self._cmd("LOGIN", user, passwd)
> 
> File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_webmail/lib/imaputils.py" in _cmd
>   213.             typ, data = self.m._simple_command(name, *args)
> 
> File "/usr/lib/python2.7/imaplib.py" in _simple_command
>   1087.         return self._command_complete(name, self._command(name, *args))
> 
> File "/usr/lib/python2.7/imaplib.py" in _command
>   869.             self.send('%s%s' % (data, CRLF))
> 
> File "/usr/lib/python2.7/imaplib.py" in send
>   257.         self.sock.sendall(data)
> 
> File "/usr/lib/python2.7/socket.py" in meth
>   224.     return getattr(self._sock,name)(*args)
> 
> Exception Type: UnicodeEncodeError at /webmail/
> Exception Value: 'ascii' codec can't encode character u'\xe7' in position 30: ordinal not in range(128)
