### ISSUE TITLE
Webmail not sending mails

### ISSUE THREAD

**Issue by monsterstrumpf** [modoboa/modoboa-webmail#140]
When trying to send a mail via the Webmail with any user, i don't get an error but nothing happens. The fields clear themselves and when i look into the "Sent"-Folder nothing appears there. Incoming Mails work great.

I don't know where to look. In the mail.log is no entry when trying to send a mail from webmail.

Hope to get help here.

Wish you all a happy new year :-)

**Comment by tonioo** [comment]
@monsterstrumpf Happy new year too. Could you open a javascript debugger to see what happens?

**Comment by monsterstrumpf** [comment]
I found out that there is a source map missing....

> Source-Map-Error: request failed with status 404
> Ressource-Address: https://***/sitestatic/jquery/jquery.min.js
> Source-Map-Address: jquery.min.map

Could that be the problem? I am not very common with the debugger, so maybe there is much more to find out but not without help ;) If interested, i could give you an testaccount to look for the problem.

Thanks in advance

**Comment by monsterstrumpf** [comment]
Problem solved!

It was only a configuration issue in postfix main.cf. The interface was wrong.

Thank you for the help !

Greetz
