### ISSUE TITLE
Webmail Issue 

### ISSUE THREAD

**Issue by nizammufid** [modoboa/modoboa-webmail#143]
![image](https://user-images.githubusercontent.com/17964885/35262549-12024fe4-0050-11e8-8d1f-9de0cf8cec7c.png)
i having some issue on the webmail and the modoboa is the latest one

**Comment by tonioo** [comment]
@nizammufid Can you give more information please?

**Comment by tonioo** [comment]
@nizammufid ping

**Comment by nizammufid** [comment]
i already solve the issue by recreate the ubuntu and not to run apt-get ugrade
