### ISSUE TITLE
fragmented recipient

### ISSUE THREAD

**Issue by AmazingBeu** [modoboa/modoboa-webmail#147]
When i try to send mail, the recipient is fragmented letter by letter.
The mail looks normal but when I click on "send", it fragments the recipient.

this is the mail sent :
![capture](https://user-images.githubusercontent.com/26152831/35408343-06ebeffa-020f-11e8-8a83-149307ad0dbe.PNG)

and of course, postfix cry :
![capture](https://user-images.githubusercontent.com/26152831/35408544-d0d4d8d6-020f-11e8-802e-ce0dbbac3750.PNG)

Modoboa 1.10 and full up-to-date
Debian 9 LXC - mysql

**Comment by tonioo** [comment]
I think PR https://github.com/modoboa/modoboa/pull/1364 fixes this issue.

**Comment by tonioo** [comment]
@AmazingBeu Have you tried using modoboa 1.10.1?

**Comment by AmazingBeu** [comment]
@tonioo Yes, it's fixed!
