### ISSUE TITLE
IOError at /contacts/

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa-webmail#152]
If you click in the webmail on contacts you got this error:
![image](https://user-images.githubusercontent.com/31078768/35680526-ea6a91c8-075a-11e8-9d15-7b03b4423ea9.png)

BR

**Comment by WASDIT** [comment]
![image](https://user-images.githubusercontent.com/31078768/35680573-11686d54-075b-11e8-931c-89934de2a842.png)

**Comment by tonioo** [comment]
@WASDIT It happens because you set DEBUG to True. Set it to False, reload and it should work again.

**Comment by WASDIT** [comment]
Hey, thank you, i really forget to disable it the last time.
