### ISSUE TITLE
Message Body is empty

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa-webmail#153]
### Info:
- Modoboa: 1.10.2
- Webmail: 1.4.1
- Installer: yes
- Upgraded with pip to the current versions

my mail contents are empty and I don't see any errors in 
- /var/log/mail.log
- /var/log/nginx/access.log
- /var/log/nginx/error.log
- /var/log/uwsgi/app/modoboa_instance.log
- and on the website itself

![screen shot 2018-02-12 at 13 43 37](https://user-images.githubusercontent.com/2507586/36097319-c2e2735c-0ffa-11e8-9b40-8e246a50c259.jpeg)

Is there somewhere else to look? Something to enable? A similar issue I haven't found yet?

**Comment by tonioo** [comment]
@danielsatanik Does it happen with all messages?

**Comment by danielsatanik** [comment]
@tonioo yes it does

**Comment by tonioo** [comment]
@danielsatanik Have you tried with DEBUG set to True?

**Comment by danielsatanik** [comment]
Inside Modoboa instance/instance/settings.py?
Yes

![screen shot 2018-02-15 at 18 08 37](https://user-images.githubusercontent.com/2507586/36270181-5b659c94-127b-11e8-938e-dda1a560b7dd.jpeg)

**Comment by tonioo** [comment]
Yes and do not forget to reload apache. Once done, please use a javascript debugger to inspect responses sent by the server.

**Comment by danielsatanik** [comment]
I get the following error in the JS console
```
Refused to display 'https://mail.example.com/webmail/getmailcontent?mbox=INBOX&mailid=271&links=1' in a frame because it set 'X-Frame-Options' to 'DENY'.
```

My nginx-conf doesn't use this option, but it is in settings.py enabled.
I enabled it myself because the option `python manage.py check --deploy` suggested I should do it. Is there a different option I should choose instead of "DENY"?

I will try "SAMEORIGIN" for now and see if it fixes it.

**Comment by danielsatanik** [comment]
It worked setting it to SAMEORIGIN, thank you. I guess you can close it now, but maybe you should adapt the check option then
