### ISSUE TITLE
KeyError at /webmail/ - Inbox at new user

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa-webmail#154]
see screenshot
![image](https://user-images.githubusercontent.com/31078768/37405114-1e902d7e-2794-11e8-95da-336d27629722.png)

**Comment by WASDIT** [comment]
Its only at language: čeština

**Comment by tonioo** [comment]
@WASDIT Can you provide the full stack trace please?

**Comment by WASDIT** [comment]
After change the language to german and then back to čeština, it worked now....
so i can not give you at the moment the full stack trace, sorry
