### ISSUE TITLE
Problems Webmail

### ISSUE THREAD

**Issue by kryskool** [modoboa/modoboa-webmail#156]
_From @carbans on March 12, 2018 16:43_

# Impacted versions

* Modoboa: 1.10.3
* installer used: Yes/No ? Yes
* Webserver: Nginx

# Steps to reproduce
When I log in, a dialogue box appears that tells me that I have a problem. The INBOX folders doesn't load.
I have 1.4.1 version of Webmail.

# Video/Screenshot link (optional)
https://imgur.com/a/UFoHO

_Copied from original issue: modoboa/modoboa#1433_

**Comment by niko-lay** [comment]
Thinks #159 is same issue

**Comment by carbans** [comment]
I have updated modobo-webmail, and the problems are solving, I think that the problems occur because INBOX is empty, but I do not 100% sure
