### ISSUE TITLE
Inline Pictures dont show

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa-webmail#158]
Hello Antonioo,
if a user got a mail and open it in the Webmail the inserted Picture wont showed.

![image](https://user-images.githubusercontent.com/31078768/38374086-1c0dd9f0-38f3-11e8-8f09-87c8af8375f6.png)

![image](https://user-images.githubusercontent.com/31078768/38374096-22abb354-38f3-11e8-9c6e-60b5b6dcb20a.png)

BR

**Comment by WASDIT** [comment]
Any Ideas @tonioo

**Comment by WASDIT** [comment]
@tonioo are you here?

**Comment by WASDIT** [comment]
@tonioo any news?

**Comment by kryskool** [comment]
Hi @WASDIT 

Did you use [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) ? 

Regards,

**Comment by WASDIT** [comment]
@tonioo @kryskool any ideas? news?

**Comment by WASDIT** [comment]
@tonioo thanks for the solution, should  i fix it manually or wait for the update?
When manually have you a short guide?

**Comment by WASDIT** [comment]
@tonioo PING??

**Comment by tonioo** [comment]
@WASDIT If you're not satisfied with the way free software work, go for a paid support plan.

**Comment by WASDIT** [comment]
@tonioo hey, why you think i am not satisfied? i ask only if i should update it manual or wait for the next release? i am now a little bit confused.

**Comment by tonioo** [comment]
@WASDIT Asking something using only uppercase letters is something I really hate... Modoboa is a free software and I'm not paid to work on it so I answer when I can.
Nevermind, you can fix it manually in a hurry. A new version should be released soon.

**Comment by WASDIT** [comment]
Hey, sorry was not intentionally.
What is the path to the file where i have to change the code?
BR
