### ISSUE TITLE
Force to change password, mailbox quota exceeded and max emails that can be sent

### ISSUE THREAD

**Issue by 8Cris1** [modoboa/modoboa-webmail#164]
Hi, have modoboa-webmail these three features?

1. Force mail user to change password after n days
2. Warning when mailbox quota exceeded
3. Set the maximum number of emails that can be sent

Is it possible to activate them?

Thanks

**Comment by tonioo** [comment]
@8Cris1 Those features are not currently implemented in Modoboa.

**Comment by 8Cris1** [comment]
thanks
