### ISSUE TITLE
accessing junk folder produces internal error

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-webmail#171]
Hi,

On one account (admin) accessing the junk folder produces an internal error.

Clues remedies anyone?

regards,
JBR

PS: after a restart it says:
```

Sorry

The requested page does not exist.

```

**Comment by tonioo** [comment]
Does your admin account has a mailbox?

**Comment by JayBeRayBearGun** [comment]
you may have a point there! :)
