### ISSUE TITLE
Webmail error with STARTTLS

### ISSUE THREAD

**Issue by 0xNeffarion** [modoboa/modoboa-webmail#179]
I'm getting the following error when trying to open the Modoboa webmail once I enable STARTTLS on IMAP settings

`
Error: Connection to IMAP server failed: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
`

**Comment by tonioo** [comment]
@0xNeffarion Which python version? What port did you configure?

**Comment by tonioo** [comment]
@0xNeffarion Try using port 993 (imaps). Modoboa webmail does not propose STARTTLS for IMAP yet because Python2 does not... We're going to drop python2 support soon and then, we'll propose STARTTLS for IMAP.

**Comment by 0xNeffarion** [comment]
How do I make it use IMAPS? Do I just change the port to 993?

**Comment by tonioo** [comment]
Yes.


Le 30/10/2018 à 14:42, Vasco a écrit :

**Comment by 0xNeffarion** [comment]
@tonioo Thank you, it works now.

Something aside though, I tried to make SMTP only work with SSL/TLS (by checking the box on the picture instead of STARTTLS) and it doesn't work when I try to connect to it via Thunderbird. Is there something else needed?
