### ISSUE TITLE
Internal Error when trying to open mail with attached files with accent mark on filenames

### ISSUE THREAD

**Issue by sibuxiang** [modoboa/modoboa-webmail#186]
# Impacted versions

* Modoboa: 1.31.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Send a pdf file with a name including an accent mark on vowel (Ex. canción)

The email receiver(modoboa user) can't open the mail getting a little box saying "internal error"

This is a problem when spanish speaking clients are using the mail client, sending and receiving files with accent marks is frequent.

# Current behavior

# Expected behavior

It should open the mail normally

# Video/Screenshot link (optional)

**Comment by WonderingDane** [comment]
I have the same issue. Attaching a file with Danish characters, such as Æ Ø Å, will give you an "internal error" when trying to open the email in the Modoboa webmail.

**Comment by monasax** [comment]
the same for Cyrillic symbols

**Comment by redfox7691** [comment]
Same error here in Italy: I cannot view a message with pdf named **valeria.arnò.pdf**. If you can point me to a "debug guide" I'll try to resolve this issue, I don't know what is best practice to debug modoboa project...
Tnx, Claudio

**Comment by tonioo** [comment]
See #189
