### ISSUE TITLE
UnicodeEncodeError at /webmail/

### ISSUE THREAD

**Issue by EDV4BIZ** [modoboa/modoboa-webmail#189]
Request Method: | GET
-- | --
https://xxxxxxx.xx/webmail/?action=viewmail&mbox=INBOX&mailid=56426&_=1560945034507
1.11.9
UnicodeEncodeError
'ascii' codec can't encode character u'\xe4' in position 15: ordinal not in range(128)
/usr/lib/python2.7/urllib.py in urlencode, line 1343
/usr/bin/uwsgi-core
2.7.13
['.',  '',  '/srv/modoboa/env/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/modoboa/env/lib/python2.7/lib-tk',  '/srv/modoboa/env/lib/python2.7/lib-old',  '/srv/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages',  '/srv/modoboa/env/lib/python2.7/site-packages']
Mi, 19 Jun 2019 13:51:37 +0200

**Comment by EDV4BIZ** [comment]
@tonioo do you have any solution?

**Comment by tonioo** [comment]
@EDV4BIZ I need to complete trace to answer you.

**Comment by EDV4BIZ** [comment]
How can i send it to you private?

**Comment by tonioo** [comment]
Send it to tonio@ngyn.org.

**Comment by EDV4BIZ** [comment]
@tonioo any updates?

**Comment by EDV4BIZ** [comment]
@tonioo anything?

**Comment by EDV4BIZ** [comment]
@tonioo sorry to bother you, but there are any updates?

**Comment by AmazingBeu** [comment]
@tonioo FYI the problem appears when the attachment has a special character in its name

Python 2.7 has the problem, not Python 3.6.

**Comment by tonioo** [comment]
What version of the webmail plugin do you use?

**Comment by EDV4BIZ** [comment]
@tonioo Webmail | 1.5.0
