### ISSUE TITLE
AUTHENTICATIONFAILED

### ISSUE THREAD

**Issue by XiaotianZha** [modoboa/modoboa-webmail#190]
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
An error happened when open the web-mail
`Error: ['[AUTHENTICATIONFAILED] Authentication failed.']`

Is there any configuration I missed?

**Comment by tonioo** [comment]
@XiaotianZha Have you checked log files?

**Comment by francogp** [comment]
I have the same issue. No error in logs
