### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jahswant** [modoboa/modoboa-webmail#192]
Modoboa | 1.14.0
Webmail | 1.5.0

I tried to upgrade my webmail from 1.5 to 1.6 by uploading the files to my server. This was to solve attachments forwarding issues. Everything was working correctly until I rebooted the server. I get this error. Even downgrading doesn't work. 

`jquery.min.js:5 POST `https://mail.xxxx-xxx.com/webmail/?action=compose` 500 (Internal Server Error)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
sendmail @ webmail.js:1052
i @ jquery.min.js:3
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
VM387:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:3)
    at Webmail.<anonymous> (webmail.js:1062)
    at Object.i (jquery.min.js:3)
    at c (jquery.min.js:3)
    at Object.fireWith [as rejectWith] (jquery.min.js:3)
    at k (jquery.min.js:5)
    at XMLHttpRequest.r (jquery.min.js:5)
parseJSON @ jquery.min.js:3
(anonymous) @ webmail.js:1062
i @ jquery.min.js:3
c @ jquery.min.js:3
fireWith @ jquery.min.js:3
k @ jquery.min.js:5
r @ jquery.min.js:5
XMLHttpRequest.send (async)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
sendmail @ webmail.js:1052
i @ jquery.min.js:3
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3`

**Comment by mussashi1981** [comment]
The problem was fixed after a reboot by itself.
What I did different was to try and send an email with attachments.
After sending that email, problem seems to have fixed by itself.
