### ISSUE TITLE
How to move mails to a folder?

### ISSUE THREAD

**Issue by cnieswand** [modoboa/modoboa-webmail#194]
I have no idea, how to move a mail to a folder … Drag & Drop? Does not work ….

**Comment by tonioo** [comment]
@cnieswand 
![Capture d’écran du 2020-03-23 10-00-34](https://user-images.githubusercontent.com/531694/77299764-4215df00-6ced-11ea-9581-c90dd83de987.png)
Click on the left icon, hold your click and move your selection.

**Comment by cnieswand** [comment]
Ups … didn't see it … maybe the icon is a bit to small … works
Thanks
