### ISSUE TITLE
Internal Error opening mail with attachment contains accent

### ISSUE THREAD

**Issue by fernandoscheffel** [modoboa/modoboa-webmail#195]
Hello all!

I'am from Brazil and using Modoboa in a debian 9.

I experienced a problem when I try to open an email with attachment when it contains accent like "~" or letter like "ç" getting Internal Error message. In outlook it opens correctly.

![screenshot](https://user-images.githubusercontent.com/52747191/78245736-5cef0d00-74be-11ea-93db-8d2922e549f0.JPG)

**Comment by tonioo** [comment]
See https://github.com/modoboa/modoboa-webmail/issues/189.
