### ISSUE TITLE
inline images not showing in webmail / image url not overwritten 

### ISSUE THREAD

**Issue by maseron** [modoboa/modoboa-webmail#202]
* Modoboa: 1.14
* installer used: Yes
* Webserver: Nginx

Can't get inline images to work in webmail. If I use html editor and send e-mail with picture, then on opening it do not show the picture. And the image url contains cid, looks like it's not overwritten...
Url to image in webmail:
<img alt="" src="cid:light@modoboa" style="width: 300px; height: 225px;" target="_blank">

Is there some configuration variable which enables that? Can't find...

**Comment by trinkel** [comment]
Was this ever resolved? I think I am having the same issue with a new install. Is there a setting I'm missing or code that I can change in the mean time?

- Modoboa: 1.17.0
- Webmail: 1.6.0
- Ubuntu: 20.04.1
- Nginx: 1.18.0-0ubuntu1

I'm happy to provide more info, just not sure what you need.

Tim

**Comment by tonioo** [comment]
@trinkel It has not been resolved yet.

**Comment by trinkel** [comment]
Thanks!
