### ISSUE TITLE
message not delivered 

### ISSUE THREAD

**Issue by dev-param** [modoboa/modoboa-webmail#213]
This is the mail system at host mail.example-info.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<example@aol.com>: host mx-aol.mail.gm0.yahoodns.net[ip] said:
    550 Action not taken (in reply to end of DATA command)

**Comment by tonioo** [comment]
@dev-param Can you provide a context, or more information?
