### ISSUE TITLE
Changing pages?

### ISSUE THREAD

**Issue by ScionOfDesign** [modoboa/modoboa-webmail#215]
Maybe I'm just missing it, but I imported a ton of emails into the webmail but I cannot for the life of me find out how to go back or forward a page. Is there an obvious button I'm missing?

**Comment by tonioo** [comment]
The webmail implements an "infinite scroll" behaviour so you just have to scroll down to the bottom of the page and it will load the next content automatically (same if you go up).

**Comment by ScionOfDesign** [comment]
Unfortunately, the intended behavior seems very erratic and inconsistent:
![Emails](https://user-images.githubusercontent.com/8867456/166648982-ddd7f0f8-64d4-40ec-b655-7afc3a5c52f9.gif)
