### ISSUE TITLE
Support for dovecot folder sharing

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-webmail#25]
_From @tonioo on December 4, 2013 16:25_

**Originally created by Miroslav Abrahám on 2013-09-02T22:45:28Z**

It would be useful for Modoboa webmail to support dovecot's folder sharing. Currently the webmail does not seem to like any virtual folders, such as "Shared" root folder for other shared folders.
When one is using the share folder plugin and has already subscribed to some folders, entering a webmail does result in a similar error message:

Error: ["Mailbox doesn't exist: Shared"]

_Copied from original issue: tonioo/modoboa#489_

**Comment by Shuro** [comment]
:+1:

**Comment by srulikuk** [comment]
Hi,
Has this feature been added? I cannot find where to set it and nothing in the documentation.
Many thanks.
