### ISSUE TITLE
How can I access webmail in a instance and send a mail

### ISSUE THREAD

**Issue by BUPT-wxq** [modoboa/modoboa-webmail#272]
I perform
pip install modoboa-webmail

MODOBOA_APPS = (
  'modoboa',
  'modoboa.core',
  'modoboa.lib',
  'modoboa.admin',
  'modoboa.relaydomains',
  'modoboa.limits',
  'modoboa.parameters',
  'modoboa_webmail',
)
$ cd <modoboa_instance_dir>
$ python manage.py load_initial_data
$ python manage.py collectstatic
$ python manage.py runserver

**Comment by tonioo** [comment]
@BUPT-wxq Have you reloaded uwsgi?

**Comment by BUPT-wxq** [comment]
Thanks to your replay. I install modoboa-webmail in a instance. I excute command as above. 
How to reloaded uwsgi and  access webmail? 
What is url of web mail？I am not sure whether web service start. http://localhost:8000 is running.

**Comment by BUPT-wxq** [comment]
> @BUPT-wxq Have you reloaded uwsgi?
Thanks to your replay. I install modoboa-webmail in a instance. I excute command as above.
How to reloaded uwsgi and access webmail?
What is url of web mail？I am not sure whether web service start. http://localhost:8000/ is running.

**Comment by tonioo** [comment]
Are you trying to run Modoboa in "development mode" ?

**Comment by BUPT-wxq** [comment]
> Are you trying to run Modoboa in "development mode" ?
modoboa-admin.py deploy --dburl default:<database url> --domain localhost --devel instance
yes
