### ISSUE TITLE
Login Error after modoboa 2.3.0 Upgrade

### ISSUE THREAD

**Issue by smelchior** [modoboa/modoboa-webmail#273]
Hi,
after upgrading to modoboa 2.3.0 i am getting a keyerror in the session:
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/b830b4f6-da03-4b1a-a28b-15180a9f1724">
So the password does not seem to be included in it anymore?
Is the 1.9.0 version not compatible with 2.3.0 yet?

**Comment by lenovin** [comment]
Hi, 
I did get the same error also on a fresh install of modoboa version 2.3.0

**Comment by DaveSophoServices** [comment]
Also got this error. I think it's because they have moved to OAuth2, instead of storing the password in the session. I'm thinking it's not compatible, but should I roll back??? Would it even work to roll back?

**Comment by theitmachine** [comment]
Same. I read in some thread they are working on a patch.

**Comment by smelchior** [comment]
issue has been fixed with modoboa 2.3.1
