### ISSUE TITLE
 Forwarding mail from within webmail client not possible

### ISSUE THREAD

**Issue by alienmindbender** [modoboa/modoboa-webmail#30]
Hi,

when trying to forward mail from within the included webmail client the "send" button gets greyed out when pressed and nothing further is happening.
Running with debug = true sheds no light on the issue and there are no strinking entries in the log files either.
However - all other webmail client functions seem to work perfectly fine.
The frontend (1.3.4) is served via apache.

Any ideas how to fix this?

**Comment by tonioo** [comment]
Keep debug = true and launch a javascript console (firebug or similar), you should get more information.

**Comment by alienmindbender** [comment]
Thats more strinking:
```
ImportError at /webmail/
No module named extensions.webmail.lib
```
Do you need the complete firebug output? 

Since I'am not a developer I can't say if this has any significance in this case - but I had to add:

import sys
sys.path.insert(0, '/pathtoinstallation/')

to wsgi.py because I ran into the "ImportError: Could not import settings" error.
