### ISSUE TITLE
Select all button is missing

### ISSUE THREAD

**Issue by artofmailing** [modoboa/modoboa-webmail#32]
Hello !

Not really sure if it's an bug and i post it to the right place, but i noticed the following : 
an 'Select all' square or something is really missing from the web interface :-)

If we can help contribute with adding this feature please ping me back, and will do that..

Kind regards,

**Comment by spinza** [comment]
Agreed also need this.

**Comment by ZhenyaPav** [comment]
Would be really awesome if this was added tbh
