### ISSUE TITLE
Internal error with Spanish locale (or any locale which uses tildes)

### ISSUE THREAD

**Issue by rmontagud** [modoboa/modoboa-webmail#37]
Moving from: https://github.com/tonioo/modoboa/issues/882 and expanding with a bit more of information

During my tests I see "Internal error" messages when I click on empty folders (such as drafts) but only with the Spanish locale (tried English and Italian)

Also I tried with another locale (portuguese) and I get the same Internal error, looks like something in the webmail software isn't playing nice with tildes in its localization files.

If it helps to diagnose: I installed modoboa with the installer, default locale in the system is es_ES

**Comment by tonioo** [comment]
Thank you for reporting. Looks like an issue with non ascii characters on empty folders. I'll take a look into it.
