### ISSUE TITLE
Multiple hosts for webmail

### ISSUE THREAD

**Issue by rmontagud** [modoboa/modoboa-webmail#38]
Is it possible to configure the webmail to support multiple hosts so it can be accessed from https://webmail.domain-a.com and https://webmail.domain-b.com

**Comment by tonioo** [comment]
You're free to configure as many vhosts as you want using nginx/apache, you just have to make sure all the domain names are listed into the ALLOWED_HOSTS setting.

**Comment by rmontagud** [comment]
Seems i'm bad enough at reviewing the config files, i've just seen it after you mentioned it, thank you
