### ISSUE TITLE
Search in webmail sent items returns an error message "Empty mailbox"

### ISSUE THREAD

**Issue by emestels** [modoboa/modoboa-webmail#40]
When performing a search in sent items folder, the system returns an error message "Empty mailbox" what ever you are searching for.
![webmail - mozilla firefox_2016-08-04_11-12-58](https://cloud.githubusercontent.com/assets/8982895/17396625/7f4c523e-5a34-11e6-8f4f-e420f2aa6aa9.png)

**Comment by tonioo** [comment]
What version do you use?
This message appears when your search does not return any result... Have you tried to play with the search options ? (click on the icon near the input)

**Comment by tonioo** [comment]
@emestels ping
