### ISSUE TITLE
Moving message between folders in modoboa webmail keeps the original message in old folder's cur dir in filesystem

### ISSUE THREAD

**Issue by tkosars** [modoboa/modoboa-webmail#43]
Hi!

Newbie here. Just installed a fresh 1.6.0 modoboa instance on a cleanly installed Debian 8.5 system.
Everything is working great, but when i move messages between folders in modoboa-webmail, the original message stays in the 'cur' folder in the filesystem. The affected IMAP folders are updated properly, but not on the filesystem level.

When i move messages with other IMAP clients (tested with a local roundcube instance, remote Outlook 2016, Windows 10 Mail) the message properly deleted from the filesystem as well from the old folder.

Is this a dovecot issue or the modoboa-webmail moves the message using a strange IMAP method?

Grats for this awesome app!

**Comment by tonioo** [comment]
Actually, the webmail only flags the message as deleted and it will be removed by dovecot during the "expunge" process. (an explanation can be found here: http://kb.mozillazine.org/Deleting_messages_in_IMAP_accounts)

You can then "compress" your inbox to remove all flagged messages.
![selection_008](https://cloud.githubusercontent.com/assets/531694/18836683/54b64b50-8401-11e6-8511-be44eb92a985.png)

**Comment by tkosars** [comment]
Many thanks for the info!

Modoboa is amazing :)

**Comment by tonioo** [comment]
Thank you :)
I close the issue since there is nothing more to do.
