### ISSUE TITLE
Error when opening messages

### ISSUE THREAD

**Issue by adeel** [modoboa/modoboa-webmail#49]
I just upgraded to 1.6.1 and now when I click on a message in my inbox (or in any other folder), I get an error message, a red box saying

> Sorry
> An internal error occured.

In some sense this is actually an improvement, because before upgrading I would only see a blank white frame.  Maybe there's an error message being logged somewhere?  Where should I check?

**Comment by tonioo** [comment]
Hi,
can you set DEBUG to True inside settings.py and reload uwsgi. You should get a complete error (directly or using firebug or similar)

**Comment by adeel** [comment]
Hm, now I get an error immediately after logging in:

```
AttributeError at /user/

'User' object has no attribute 'group'

Request Method: 	GET
Request URL: 	https://mail.x.y/user/
Django Version: 	1.9.9
Exception Type: 	AttributeError
Exception Value: 	

'User' object has no attribute 'group'

Exception Location: 	/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py in inner, line 205
Python Executable: 	/usr/bin/uwsgi-core
Python Version: 	2.7.12
Python Path: 	

['.',
 '',
 '/srv/modoboa/env/lib/python2.7',
 '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/modoboa/env/lib/python2.7/lib-tk',
 '/srv/modoboa/env/lib/python2.7/lib-old',
 '/srv/modoboa/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/modoboa/env/local/lib/python2.7/site-packages']

Server time: 	Wed, 2 Nov 2016 09:54:12 +0100
```

**Comment by tonioo** [comment]
Looks like your extensions are not up-to-date. Please update them.

**Comment by adeel** [comment]
I'm not very familiar with Django, is there somewhere I can see a list of all the relevant extensions?

**Comment by tonioo** [comment]
I'm talking about Modoboa extensions and you should be notified automatically if you've enabled the feature. http://modoboa.org/en/weblog/2016/10/12/modoboa-161-available/

**Comment by adeel** [comment]
Ok, thanks.  After doing that I'm able to log in again.  But now when I open any email I got the blank white frame where the message should be.  If I right-click and choose "View Frame Info", it says that the URL of the page is about:blank.

**Comment by tonioo** [comment]
Have you tried using a javascript debugger like I proposed ?

**Comment by adeel** [comment]
Wow, thanks, it turned out to be an "add_header X-Frame-Options DENY" directive I had hidden in my nginx configuration.  It's working now, thanks for your help :)
