### ISSUE TITLE
Selection of multiple message to delete/mark as read/unread

### ISSUE THREAD

**Issue by tonioo** [modoboa/modoboa-webmail#5]
_From @emestels on February 11, 2015 13:15_

Hi,

In the inbox, in order to select multiple mail messages to apply an action (delete - mark as read - mark as unread) we need to use keyboard ctrl + click
==> it not possible with a touch screen device!
Simple click/touch of the check box should activate the select
![webmail - mozilla firefox_2015-02-11_14-09-08](https://cloud.githubusercontent.com/assets/8982895/6147483/56842eac-b1f8-11e4-9199-a152f7d25dcc.png)

_Copied from original issue: tonioo/modoboa#692_

**Comment by vingeni** [comment]
works fine for me, with modoboa and modoboa-webmail on master branch
HEAD is : 
- modoboa: 4d0ee14a8073c6a035e5cd8df7331cfc193b2f07
- modoboa-webmail: cf7b86b3d8b084fb3d4e76b08846e04e21a4ac4d

**Comment by tonioo** [comment]
Great! Thanks for checking.

**Comment by KarlBaumann** [comment]
This feature still does not work as expected. You are not able to select all messages, and Shift + Click behavior is also very veird
