### ISSUE TITLE
Release notes missing

### ISSUE THREAD

**Issue by almereyda** [modoboa/modoboa-webmail#50]
The git tags, represented as Releases in GitHub, don't contain release notes, which makes it hard for a third-party developer to follow the changes in development.

**Comment by tonioo** [comment]
How can I add a release note to a tag ?

**Comment by almereyda** [comment]
I think only after it has been pushed to GitHub directly within their UI.
That's also where you add binary releases and docs links.

**Comment by tonioo** [comment]
Ok I see. Do you know if it can be linked to a milestone ?

**Comment by tonioo** [comment]
Done (https://github.com/modoboa/modoboa-webmail/releases)
