### ISSUE TITLE
can anyone help add draftjs to this webmail client

### ISSUE THREAD

**Issue by hadifarnoud** [modoboa/modoboa-webmail#52]
draft.js is simple and light. it has auto text direction (RTL,LTR) as well.
https://facebook.github.io/draft-js/

I need some guidance to remove CKEditor and add this one to webmail. I quite like Modoboa Webmail, it's very simple and that's what we need for our users. this RTL issue is the only blocking issue we have

PS: it can be configured to have more advanced features but out of the box it's very simple editor. examples here for <textarea> https://github.com/sstur/react-rte

**Comment by tonioo** [comment]
@hadifarnoud Removing CKeditor is not so easy and it requires to modify the webmail javascript code. But, let users choose which editor they want to use is something interesting. I'll think about an easy way to do that.
About CKeditor, I saw you tried to enable the BiDi button but don't forget it is a plugin and that you have to install it aside CKeditor. Modifying the toolbar is not enough.

**Comment by hadifarnoud** [comment]
I think draftjs is good enough to replace CKEditor all together. it automatically changes text direction as you type. neat! 

It may be helpful to add BiDi button. if the way I did it is not enough, please do tell me what to do. I'll send a PR for it

**Comment by tonioo** [comment]
draft.js requires react.js which is not currently used by the webmail. I don't want to introduce side effects so it needs more tests. About CKEditor, I think its documentation is the best place to start: http://docs.ckeditor.com/#!/guide/dev_plugins.

**Comment by hadifarnoud** [comment]
I was able to add BiDi by editing this file /srv/www/mododemo/sitestatic/js/editor_config.js
just not sure where this file is on this repo. do you just generate this file?

**Comment by tonioo** [comment]
Actually, this file is provided by the core of Modoboa. Looks like I forgot to move it to the webmail when I splitted the repositories... I'll move this file to the webmail repository.

**Comment by hadifarnoud** [comment]
It would be great to just add BiDi button to your editor. this is stopping us to update modoboa because I have to again edit it by hand (and not sure it works since you changed it)

**Comment by tonioo** [comment]
@hadifarnoud The BiDi plugin is not enabled by default within Modoboa. Look at https://github.com/modoboa/modoboa/issues/1076 for addtional information. It will be released with 1.7.2.
