### ISSUE TITLE
move messages to mail folders

### ISSUE THREAD

**Issue by oconshaw** [modoboa/modoboa-webmail#56]
How does one move a message to a mail folder in webmail?  
Also, I can see how to create and delete a new mailbox folder.  But, when I go to the server in /srv/vmail/user account/Maildir I can see that the folder is still there.

Does it eventually get deleted somehow?

Thanks.

# Impacted versions

* Modoboa: 1.6.3
* installer used: Yes
* Webserver: Nginx
# Steps to reproduce

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by tonioo** [comment]
You can drag&drop messages to the Trash folder. (look at first column on the left.)
Dovecot is in charge of deleting mailboxes and modoboa sends IMAP command to create/delete mailboxes.

**Comment by tonioo** [comment]
@oconshaw ping
