### ISSUE TITLE
error at sending email

### ISSUE THREAD

**Issue by amarildo** [modoboa/modoboa-webmail#58]
Hello, when i try to send email from wemail, i receive http error 500 with message "'module' object has no attribute 'get_globa_parameters'"

i believe is a typo in modoboa_webmail/lib/sendmail.py

strange enough it worked till today

ps: great job with modoboa

**Comment by tonioo** [comment]
@amarildo Thanks for reporting. I guess you've upgraded your platform to 1.7.0 and new plugins. This typo was introduced by version 1.1.0 of the webmail plugin.
