### ISSUE TITLE
['[AUTHENTICATIONFAILED] Authentication failed.']

### ISSUE THREAD

**Issue by ronaldpatino** [modoboa/modoboa-webmail#68]
Hi I am getting the following when using webmail, modoboa is running on

ubuntu 16.04 
Modoboa 1.7.0

When using web mail I get in the ui
['[AUTHENTICATIONFAILED] Authentication failed.']

And enabling debug in dovecot I get:

mail dovecot: auth: Debug: sql(user@mailserver.com,127.0.0.1,<wosZRp9NrNZ/AAAB>): query: SELECT email AS user, password, '/srv/vmail/mailserver.com/user' AS userdb_home, 1002 AS userdb_uid, 1002 AS userdb_gid, CONCAT('*:bytes=', mb.quota, 'M') AS userdb_quota_rule FROM core_user u INNER JOIN admin_mailbox mb ON u.id=mb.user_id INNER JOIN admin_domain dom ON mb.domain_id=dom.id WHERE email='user@mailserver.com' AND is_active AND dom.enabled

dovecot: auth: sql(user@mailserver.com,127.0.0.1,<wosZRp9NrNZ/AAAB>): Password mismatch (given password: ...

mail dovecot: auth: Debug: sql(no-reply@colineal.com,127.0.0.1,<wosZRp9NrNZ/AAAB>): SHA512-CRYPT(#0361{#002E���ux�#033m�]�����oZ�6Ţ��<;L#023) != '$6$rounds=70000 ...

imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<user@mailserver.com>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<wosZRp9NrNZ/AAAB>
Apr 20 20:49:16 mail dovecot: auth: Debug: client passdb out: FAIL#0111#011user=user@mailserver.com

**Comment by tonioo** [comment]
@ronaldpatino This issue has already been fixed. Please upgrade to modoboa 1.7.3 and make sure to follow upgrade instructions for 1.7.1 and 1.7.2. (http://modoboa.readthedocs.io/en/latest/upgrade.html#id2 and http://modoboa.readthedocs.io/en/latest/upgrade.html#id1)
