### ISSUE TITLE
Wrong data format

### ISSUE THREAD

**Issue by gdassori** [modoboa/modoboa-webmail#81]
In this view:
https://webmail.website/webmail/#?action=viewmail&mbox=INBOX&mailid=5

the From and To value are malformed, looks like they're a List of Unicode strings:

From	[u'Alex']
To	[u'Guido']

Also, when replying I have in the "To" form:
[u'Alex <alex.lowe@gmail.com>']
Causing the form to fail with the error "Enter a valid email address."
And, in the body, also:
[u'Alex <alex.lowe@gmail.com>'] wrote:

Debian8,1, Python2.7.9

**Comment by tonioo** [comment]
See #76
