### ISSUE TITLE
Getmailcontent yields error on first try

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa-webmail#87]
# Impacted versions

* Modoboa: 1.8.2
* installer used: Yes (configured cfg, no amavis)
* Webserver: Nginx

# Steps to reproduce
On may installation it happens every time an unread message is opened.
When the message is read it works fine. So reloading works.
Setting the message back to unread, yields the same problem.

# Current behavior
A red banner is displayed, informing about an internal error.

# Expected behavior
Mail content should be displayed.

# Video/Screenshot link (optional)

<img width="608" alt="screen shot 2017-07-29 at 05 27 50" src="https://user-images.githubusercontent.com/2507586/28741801-13c72948-741f-11e7-853f-610c13a8d3ee.png">

**Comment by tonioo** [comment]
Please set DEBUG to True inside /srv/modoboa/instance/instance/settings.py and reload uwsgi. You should get a complete trace.

**Comment by danielsatanik** [comment]
This is the beginning of the stacktrace, as it is in the webmail it is a html code, so I took a screenshot:

<img width="918" alt="screen shot 2017-07-29 at 16 02 11" src="https://user-images.githubusercontent.com/2507586/28745380-6f05d158-7477-11e7-81a1-4e3bda90b351.png">

Does this error ring a bell? Have you encountered that already?

**Comment by tonioo** [comment]
@danielsatanik Ok, the trace is indeed useful. Can you tell me what is your dovecot version please?

**Comment by danielsatanik** [comment]
my dovecot version is 2.2.27
