### ISSUE TITLE
Mail Image View

### ISSUE THREAD

**Issue by WASDIT** [modoboa/modoboa-webmail#91]
If another User send a Mail with an image (not as attachment) in the body, and you try to open it in the Webmail Inbox, it is not showed, already set in the options from text to html but still the same. In the Mailclient it is shown.

**Comment by tonioo** [comment]
@WASDIT Actually the problem comes from the configuration file.

Edit your settings.py file, look for this line at the beginning:
```python
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
```
and replace it by this one:
```python
BASE_DIR = os.path.realpath(os.path.dirname(os.path.dirname(__file__)))
```
Then reload uwsgi.

I'll fix this in the next modoboa release.

**Comment by WASDIT** [comment]
Hey, if i changed that, it is still the same but i can not recieve mails anymore.

**Comment by WASDIT** [comment]
Ok the mail recieving now working but it need longer, but there is still not showing it.
