### ISSUE TITLE
Empty mail causes error

### ISSUE THREAD

**Issue by buttch** [modoboa/modoboa-webmail#96]
# Impacted versions
    Modoboa: 1.9.0

# Steps to reproduce
Try open empty mail.

# Current behavior
Internal error - 
![emptymailerror](https://user-images.githubusercontent.com/13139675/30514991-7433d3f8-9b20-11e7-8f26-6b96120c38be.PNG)

**Comment by tonioo** [comment]
@buttch Can you set DEBUG to True inside settings.py, reload uwsgi and try again?

**Comment by tonioo** [comment]
@buttch ping

**Comment by buttch** [comment]
Sorry I have no time to help now.

I will as soon as possible.

Regards

13.10.2017 17:54 "Antoine Nguyen" <notifications@github.com> napisał(a):
